<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>latest</LangVersion>
        
        <AssemblyName>generatedAssemblyName</AssemblyName>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>bin\Debug\</OutputPath>
    </PropertyGroup>


    <PropertyGroup>
        <!-- Credits to https://til.cazzulino.com/msbuild/how-to-get-user-home-dir-cross-platform for this! -->
        <UserProfileHome Condition="'$([MSBuild]::IsOSUnixLike())' == 'true'">$(HOME)</UserProfileHome>
        <UserProfileHome Condition="'$([MSBuild]::IsOSUnixLike())' != 'true'">$(USERPROFILE)</UserProfileHome>
    </PropertyGroup>

    <PropertyGroup>
        <!-- Windows typical steam path -->
        <SteamPath Condition="Exists('C:\Program Files (x86)\Steam')">
            C:\Program Files (x86)\Steam
        </SteamPath>

        <!-- koja mori's steam path -->
        <SteamPath Condition="'$(SteamPath)' == '' And Exists('$(UserProfileHome)\Applications\Steam')">
            $(UserProfileHome)\Applications\Steam
        </SteamPath>
        
        <!-- MacOS typical steam path -->
        <SteamPath Condition="'$(SteamPath)' == '' And Exists('$(UserProfileHome)\Library\Application Support\Steam')">
            $(UserProfileHome)\Library\Application Support\Steam
        </SteamPath>

        <!-- fallback -->
        <SteamPath Condition="'$(SteamPath)' == ''">
            C:\Program Files (x86)\Steam
        </SteamPath>
    </PropertyGroup>

    <PropertyGroup>
        <SFSPath>
            $(SteamPath)\steamapps\common\Spaceflight Simulator\Spaceflight Simulator Game
        </SFSPath>

        <ModsFolder>
            $(SFSPath)\Mods
        </ModsFolder>
    </PropertyGroup> 

    <Target Name="VerifySFSPath" BeforeTargets="CoreCompile;PrepareForBuild">
        <Message Text="Spaceflight Simulator path resolved via XML conditions to: $(SFSPath)" Importance="High" />
    </Target>

    <ItemGroup>
        <Reference Include="$(SFSPath)\Spaceflight Simulator_Data\Managed\*.dll">
            <Private>false</Private>
        </Reference>

        <!-- Mod References  =====================================================-->

        <Reference Include="UITools" Condition="Exists('$(SFSPath)\Mods\UITools')">
            <HintPath>$(SFSPath)\Mods\UITools\UITools.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <Reference Include="UniLog" Condition="Exists('$(SFSPath)\Mods\UniLog')">
            <HintPath>$(SFSPath)\Mods\UniLog\UniLog.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <!-- ===================================================================-->
    </ItemGroup>

    <PropertyGroup>
        <EnableModCopy>$autoCopyMod$</EnableModCopy>
    </PropertyGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="Exists('$(SFSPath)') And '$(EnableModCopy)' == 'true'">
        <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFolder="$(ModsFolder)\$(AssemblyName)\" />
    </Target>

</Project>