name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore
        run: dotnet restore

      - name: Pack Template
        shell: pwsh
        run: |
          $out = Join-Path $PWD "bin\Release"
          dotnet pack ".\kojamori.SFS.Templates.CodeMod.csproj" -c Release -o $out

      - name: Publish to NuGet.org
        shell: pwsh
        run: |
          dotnet nuget push "bin\Release\*.nupkg" `
            --api-key "${{ secrets.NUGET_API_KEY }}" `
            --source "https://api.nuget.org/v3/index.json" `
            --skip-duplicate
